package java_quetico_trip_planner;

import javax.swing.JOptionPane;

/**
 * Splash JFrame
 * 
 * This dialog will display a graphic and a menubar which allows you to
 * navigate to other areas of the trip planner.
 *
 * @author cleblanc
 */
public class JFrameSplash extends javax.swing.JFrame {

    /**
     * Splash JFrame
     *
     * Creates all of the components for the JFrame dialog.
     */
    public JFrameSplash()
    {
        initComponents();
        setCustomFrameProperties();
    }

    /**
     * Set Custom Frame Properties
     *
     * Set any custom frame properties not specified by NetBeans.
     */
    private void setCustomFrameProperties()
    {
        // Disable resizing
        this.setResizable(false);

        // Set the window size (since NetBeans wont)
        this.setSize(360, 300);

        // Center the frame on the screen
        this.setLocationRelativeTo(null);

        // Set the custom icon
        javax.swing.ImageIcon LogoIconImage =
            new javax.swing.ImageIcon("icon.jpg");
            java.awt.Image LogoIcon =
            LogoIconImage.getImage();
            setIconImage(LogoIcon);
    }

    /**
     * Set Trip Information JFrame Visible
     *
     * Draws the trip information jframe
     */
    public void setTripInformationJFrameVisbile()
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new JDialogSelectTrip().setVisible(true);
            }
        });
    }

    /**
     * Se Canoe Selection JFrame Visible
     *
     * Draws the canoe selection jframe
     */
    private void setCanoeSelectionJFrameVisible()
    {
        TripInformation ti = TripInformation.getInstance();
        if (ti.updated) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                   new JDialogSelectCanoes().setVisible(true);
                }
            });
        } else {
            JOptionPane.showMessageDialog(null,
                    "Please update your trip information first!",
                    "Update trip information first!",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * Set App Exit
     *
     * Exits the application
     */
    private void setAppExit()
    {
        // Dispose of the JFrame and exit
        dispose();
        System.exit(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSplashGraphic = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuEnterMaintain = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quetico Trip Planner");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSplashGraphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/java_quetico_trip_planner/canoe.jpg"))); // NOI18N
        lblSplashGraphic.setText("jLabel1");
        getContentPane().add(lblSplashGraphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, 410, 530));

        jMenu1.setFont(new java.awt.Font("Arial", 0, 11));
        jMenu1.setLabel("Trip Information");

        jMenuItem3.setFont(new java.awt.Font("Arial", 0, 11));
        jMenuItem3.setText("Retrieve");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        menuEnterMaintain.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuEnterMaintain.setFont(new java.awt.Font("Arial", 0, 11));
        menuEnterMaintain.setText("Enter/Maintain");
        menuEnterMaintain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEnterMaintainActionPerformed(evt);
            }
        });
        jMenu1.add(menuEnterMaintain);

        jMenuItem5.setFont(new java.awt.Font("Arial", 0, 11));
        jMenuItem5.setText("Write");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Arial", 0, 11));
        jMenuItem6.setText("Print");
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setFont(new java.awt.Font("Arial", 0, 11));
        jMenu2.setLabel("Canoes");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Arial", 0, 11));
        jMenuItem1.setText("Select");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Arial", 0, 11));
        jMenuItem2.setText("Enter/Maintain");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Arial", 0, 11));

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("Arial", 0, 11));
        jMenuItem4.setLabel("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuExit.add(jMenuItem4);

        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void menuEnterMaintainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEnterMaintainActionPerformed
        setTripInformationJFrameVisbile();
    }//GEN-LAST:event_menuEnterMaintainActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        setCanoeSelectionJFrameVisible();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        setAppExit();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSplash().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogMaintainCanoes().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogRetrieveTrip().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDialogWriteTrip().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel lblSplashGraphic;
    private javax.swing.JMenuItem menuEnterMaintain;
    private javax.swing.JMenu menuExit;
    // End of variables declaration//GEN-END:variables

}
